---
title: "Practice #1: Exploring R and RStudio"
date: Spatial Data Analysis and Visualization with R
output: 
  html_document: 
    css: css/plain_html.css
    includes:
      in_header: header.html
    lib_dir: lib
    self_contained: no
    smart: no
    theme: lumen
    toc: yes
    toc_float: yes
---

## Set the Working Directory to the Data Folder

```{r eval=FALSE}
setwd("../../../data") ## Or use the Session menu --> Set Working Directory
```

## Import the eviction notices dataset

Data page:  
https://data.sfgov.org/Housing-and-Buildings/Eviction-Notices/5cei-gny5

```{r}
evict_df <- read.csv("Eviction_Notices.csv")
nrow(evict_df)
```

Get just the eviction notices for just 2014. First add a year column:

```{r}
evict_df$File.Date <- as.character(evict_df$File.Date)
evict_df$year <- substr(evict_df$File.Date, nchar(evict_df$File.Date) - 3, nchar(evict_df$File.Date))
```

Use the year column as a filter.

```{r}
evict_df_2014 <- evict_df[evict_df$year=="2014",]
nrow(evict_df_2014)
```





