---
title: <span class='ex-title'>Additional Resources</span>
output: 
  html_document: 
    css: css/plain_html.css
    includes:
      in_header: header.html
    lib_dir: lib
    self_contained: no
    smart: no
    
---

<style>
ul {
}
li {
  list-style-type:square;
}
h2 {
  margin-top: 2em;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## General R Tutorials

- [Introduction to R](https://cengel.github.io/R-intro/){target="_blank"}, Claudia Engel

- [R Basics](https://sejdemyr.github.io/r-tutorials/basics/){target="_blank"}, Simon Ejdemyr

- *__swirl__*. swirl is a R package that provides tutorials right within RStudio. Install *swirl* from the 'Packages' tab in RStudio, then type *swirl()* at the console.

- [R for Data Science](http://r4ds.had.co.nz/){target="_blank"}, Garrett Grolemund and Hadley Wickham

- [DataCamp](https://www.datacamp.com/){target="_blank"}, DataCamp ($, some free)

## Spatial Data in R Tutorials

- [Using Spatial Data with R](https://cengel.github.io/R-spatial/){target="_blank"}, Claudia Engel

- [Spatial Data Analysis with R](https://ajlyons.github.io/rspatialdata/){target="_blank"}, Andy Lyons

- [Introduction to Working With Vector Data in R](https://www.neonscience.org/vector-data-series/){target="_blank"}, NEON

- [GIS in R Tutorial](http://www.nickeubank.com/gis-in-r/){target="_blank"}, Nick Eubank

- [Spatial data manipulation](http://www.rspatial.org/spatial/rst/3-vectordata.html){target="_blank"}, Robert  Hijmans

- [An Introduction to Spatial Data Analysis and Visualization in R](https://data.cdrc.ac.uk/tutorial/an-introduction-to-spatial-data-analysis-and-visualisation-in-r){target="_blank"}, Consumer Data Research Center

- [Introduction to GIS and Spatial Analysis](https://mgimond.github.io/Spatial/index.html){target="_blank"}, Manuel Gimond

- [Working with Geospatial Data in R](https://www.datacamp.com/courses/working-with-geospatial-data-in-r){target="_blank"}, DataCamp ($)

## Spatial Data Analysis

- [Applied Spatial Data Analysis with R](http://www.asdar-book.org/){target="_blank"}, Roger S. Bivand, Edzer Pebesma and V. G&#243;mez-Rubio. UseR! Series, Springer

- [Geocomputation with R](http://robinlovelace.net/geocompr/){target="_blank"}, Robin Lovelace, Jakub Nowosad, and Jannes Muenchow

## R Package Reviews

- <p>[Analysis of Spatial Data](https://cran.r-project.org/web/views/Spatial.html){target="_blank"}, CRAN Task View</p>

## Visualization

- [Making maps in R tutorial](https://cengel.github.io/rspatial/4_Mapping.nb.html){target="_blank"}, Claudia Engel

- [Introduction to visualising spatial data in R](https://github.com/Robinlovelace/Creating-maps-in-R){target="_blank"}, Robin  Lovelace

- [Making Maps with ggplot and ggmap](http://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html){target="_blank"},  Eric Anderson 

- [tmap](https://cran.r-project.org/web/packages/tmap/vignettes/tmap-getstarted.html){target="_blank"}

- [Leaflet for R](https://rstudio.github.io/leaflet){target="_blank"}, RStudio

## RStudio

- <p>[Webinars](https://www.rstudio.com/resources/webinars/){target="_blank"}, RStudio</p>

## R and ArcGIS

- [R-ArcGIS Bridge Tutorial](https://www.youtube.com/watch?v=9lpPuCmVmxc){target="_blank"}, ESRI

- [arcgisbinding R Package](https://r-arcgis.github.io/assets/arcgisbinding-vignette.html){target="_blank"} ESRI

## Working with Specific Datasets

- [Mapping US Census Data](http://zevross.com/blog/2015/10/14/manipulating-and-mapping-us-census-data-in-r-using-the-acs-tigris-and-leaflet-packages-3/){target="_blank"}, Zevross

- [Cal Atlas](http://www.atlas.ca.gov/download.html){target="_blank"}

- [State of CA Geoportal](http://portal.gis.ca.gov/geoportal/catalog/search/browse/browse.page){target="_blank"}


## Cheatsheets

- [ArcGIS equivalent R functions](http://www.seascapemodels.org/data/ArcGIS_to_R_Spatial_CheatSheet.pdf), SeaScapeModels.org *

- [Spatial R Remote Sensing and GIS functions](https://github.com/wegmann/RSdocs/raw/master/RSecology_cheatsheet/RS_ecology_refcard.pdf), [Remote Sensing and GIS for Ecologists](http://book.ecosens.org/) *

- [Spatial Data Reference Card](https://github.com/wegmann/RSdocs/raw/master/Cheatsheet/AniMove_refcard.pdf), [AniMove](http://animove.org/) *

- [R color cheatsheet](https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/colorPaletteCheatsheet.pdf), Melanie Frazier *

- [Overview of Coordinate Reference Systems in R](https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/OverviewCoordinateReferenceSystems.pdf), Melanie Frazier *

- [ggMap Quick Start](https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/ggmap/ggmapCheatsheet.pdf), Melanie Frazier *

- [Data Management Ultimate Cheatsheet](https://sites.ualberta.ca/~ahamann/teaching/renr690/R_Cheat_Data.pdf), Andreas Hamann *

- [RStudio Cheatsheets](https://www.rstudio.com/resources/cheatsheets/), RStudio

- [GIS in R Vector Functions](http://www.nickeubank.com/wp-content/uploads/2015/10/gis_in_r_vector_cheatsheet.pdf), Nick Eubank

\* = copy in our workshop 'Extras' folder

